version = 1

test_patterns = ["test/*.ts"]

[[analyzers]]
name = "typescript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "mocha"]
  module_system = "es-modules"
  style_guide = "google"
