version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["mocha"]

[[analyzers]]
name = "typescript"
enabled = true

  [analyzers.meta]
  environment = ["mocha"]
  
[[test_patterns]]
pattern = "test/**/*.ts"
name = "mocha"
