name: 'CI'
on:
  pull_request:
jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3         # checkout the repo
      - run: npm ci                       # install packages
      - run: npm test                     # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: test-report.json

  format-check:
    name: 'GTS Compliance'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3         # checkout the repo
      - run: npm ci                       # install packages
      # - run: npx gts check-format         # check formatting
      - run: npx gts lint src/
